# Compound Interest with Loops

print("what is the original deposit (positive value): 2000")
print("what is the interest rate (positive value):4")
print("what is the number of the months (positive value): 24")
print("what is the goal amount (can enter 0 but not negetive): -10")
print("Input must 0 or greater")
print("what is the goal amount (can enter 0 but not negetive: 20,110)")
print("Month: 1 Acount Balance is: $ 2001")
print("Month: 2 Acount Balance is: $ 2003")
print("Month: 3 Acount Balance is: $ 2005")
print("Month: 4 Acount Balance is: $ 2005")
print("Month: 5 Acount Balance is: $ 2007")
print("Month: 6 Acount Balance is: $ 2009")
print("Month: 7 Acount Balance is: $ 2011")
print("Month: 8 Acount Balance is: $ 2013")
print("Month: 9 Acount Balance is: $ 2015")
print("Month: 10 Acount Balance is: $ 2017")
print("Month: 11 Acount Balance is: $ 2019")
print("Month: 12 Acount Balance is: $ 2021")
print("It will take: 49 month to reach the goal of $ 20,110")
